## Dataset
label_file: 'dataset/train.csv'
img_cols: ['StudyInstanceUID', 'Slice']
label_cols: ['x0', 'y0', 'x1', 'y1', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
crop_cols: []
image_dir: 'dataset/train_images'
img_format: 'dcm'
bbox_label: True
vert_ratio: True
use_2dot5D: True
seq_len: null
batch_size: 64
image_size: 384
num_workers: 2
pin_memory: True
seed: 42
out_file: 'output/infer_vert_bbox_ratio.pkl'

## Model
in_chans: 3
num_classes: 11
drop_path_rate: 0.1
use_seq_layer: False
pretrained: False                       # True: load pretrained model, False: train from scratch
checkpoint_path: ''                    # Path to model's pretrained weights
checkpoint_dirs: {'convnext_tiny': ['vert_bbox_ratio_checkpoint/convnext_tiny-384/fold=0-best.pth',
                                    'vert_bbox_ratio_checkpoint/convnext_tiny-384/fold=1-best.pth',
                                    'vert_bbox_ratio_checkpoint/convnext_tiny-384/fold=2-best.pth',
                                    'vert_bbox_ratio_checkpoint/convnext_tiny-384/fold=3-best.pth',
                                    'vert_bbox_ratio_checkpoint/convnext_tiny-384/fold=4-best.pth']}
debug: False