## Dataset
input_dir: ''
kfold: 5
label_file: 'output/train_vert_bbox_fold5.csv'
img_cols: ['StudyInstanceUID', 'Slice']
crop_cols: []
label_cols: ['x0', 'y0', 'x1', 'y1', 'vertebrae']
image_dir: 'dataset/train_images'
img_format: 'dcm'
bbox_label: True
use_2dot5D: True
seq_len: null
batch_size: 64
image_size: 384
num_workers: 2
pin_memory: True
seed: 42

## Model
device: 'cuda'
model_name: 'convnext_tiny'
num_classes: 5
in_chans: 3
drop_path_rate: 0.1
use_seq_layer: False
pretrained: True                   # True: load pretrained model (may need internet for weight downloading), False: train from scratch 
checkpoint_path: ''                # Path to model's pretrained weights

## Training
n_epochs: 15
loss_fn: 'box'
weights: [0.8, 0.2]
optimizer: 'AdamW'
learning_rate: 1.0e-4
weight_decay: 1.0e-5
lr_scheduler: 'CosineAnnealingWarmRestarts' # 'CosineAnnealingLR' #
lr_scheduler_params: {
    # 'T_max': 5,
    'T_0': 5, 'T_mult': 1,
    'eta_min': 1.0e-6,
}
resume: True                       # Resume training if True
checkpoint_dir: 'vert_bbox_checkpoint'   # Directory to save new checkpoints
save_freq: 2                       # Number of checkpoints to save after each epoch
debug: False                       # Get a few samples for debugging
_metric_to_use: ['acc', 'auc']     # Metric to be used
_metric_to_opt: 'auc'              # Metric used to select and save the best checkpoint (e.g. 'loss', 'auc')
_use_tensorboard: False            # Whether to use tensorboard for logging
_use_wandb: True                   # Whether to use wandb for logging
_wandb_project: 'RSNA-vert-bbox-2022'    # Wandb's project name
_wandb_entity: 'aip490'            # Wandb's account to save experiment result
_wandb_resume_id: null             # Resume wandb logging if specify run id (e.g. '33fp7u8d')